name: Validasi Kartu Nama

on: [push, pull_request]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4

      - name: Cek Struktur HTML
        # Kita menggunakan perintah sederhana untuk memastikan file ada
        run: test -f index.html && echo "File index.html ditemukan!"